# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  welcome: circleci/welcome-orb@0.4.1
jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello"
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: |
          mkdir logs
          echo "hello" > /tmp/logs/log.txt
      - persist_to_workspace:
          root: /tmp
          paths:
            - logs/log.txt
  read_log_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/logs
      - run: echo $(ls /tmp)
      - run: echo $(ls /tmp/logs)
      - run: cat "/tmp/logs/log.txt"
workflows:
  say-hello-workflow:
    jobs:
    - welcome/run
    - print_hello:
        requires:
          - welcome/run
    - print_world:
        requires:
          - print_hello
    - read_log_file:
        requires:
          - print_world
  